language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose && docker-compose up -d --build  


script:
  - docker-compose down
  - docker-compose up -d
  - docker-compose exec web python manage.py test
  - docker-compose down

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  strategy: git
  app: cs50web-project3-pizza
  run: python manage.py migrate
  on: master