version: '3.7'

services:
  web:
    build: .
    command: gunicorn pizza.wsgi -b 0.0.0.0:8000 
    environment: 
      - ENVIRONMENT=production
      - SECRET_KEY=(g*525o8h3_ub&y(oh*_h7)9^269+ox7@ty6#5rpugjnu!i7*l
      - DEBUG=
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_XTvFZZsFJOMvhwOh6xGQZVzO00dKGJR16n
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
