# Generated by Django 3.0.5 on 2020-04-25 06:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='name'),
        ),
    ]
