# Generated by Django 3.0.5 on 2020-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], default='SM', max_length=2),
        ),
    ]
