# Generated by Django 3.0.5 on 2020-04-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200411_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
