# Generated by Django 3.0.5 on 2020-04-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuinstance',
            name='final_price',
        ),
    ]
