# Generated by Django 3.0.5 on 2020-04-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_menuinstance_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinstance',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
