# Generated by Django 3.0.5 on 2020-04-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_menuinstance_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuinstance',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
