# Generated by Django 3.0.5 on 2020-04-11 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20200411_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_dinner',
            field=models.ManyToManyField(blank=True, to='orders.Dinner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_pasta',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_pizza',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_salad',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_subs',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.Customer'),
        ),
    ]
