# Generated by Django 3.0.5 on 2020-05-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200502_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('Cart', 'cart'), ('Processing', 'processing'), ('Done', 'done')], default='Cart', max_length=20),
        ),
    ]
