# Generated by Django 3.0.5 on 2020-05-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200503_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('Cart', 'Cart'), ('Processing', 'Processing'), ('Done', 'Done')], default='Cart', max_length=20),
        ),
    ]
