# Generated by Django 3.0.5 on 2020-05-14 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200503_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinstance',
            name='n_items',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='n.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
