# Generated by Django 3.0.5 on 2020-05-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200518_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuinstance',
            old_name='dish',
            new_name='dish',
        ),
    ]
