# Generated by Django 3.0.5 on 2020-05-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200524_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinstance',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
