# Generated by Django 3.0.5 on 2020-05-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_menuinstance_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuinstance',
            options={'ordering': ['time_created']},
        ),
        migrations.AlterField(
            model_name='menuinstance',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem', verbose_name='dish'),
        ),
    ]
